# Generated by Django 2.1.2 on 2018-11-07 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_auto_20181106_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scoce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C', models.IntegerField()),
                ('python', models.IntegerField()),
                ('Django', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('sex', models.CharField(max_length=3)),
                ('tel', models.CharField(max_length=11)),
            ],
        ),
        migrations.AddField(
            model_name='scoce',
            name='Student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.Student'),
        ),
    ]
