# Generated by Django 2.1.2 on 2018-11-10 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0003_auto_20181107_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoce',
            name='C',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scoce',
            name='Django',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scoce',
            name='python',
            field=models.IntegerField(default=0),
        ),
    ]
