# Generated by Django 2.1.2 on 2018-11-14 10:20

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0004_auto_20181110_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='content',
            field=mdeditor.fields.MDTextField(default=1),
            preserve_default=False,
        ),
    ]
